### ISSUE TITLE
Add Return YouTube Dislike Feature 

### ISSUE THREAD

**Issue by nikunjarya** [ulyngs/mindshield-open-source#23]
Please add the return YouTube dislikes feature into the extension since there is no standalone extension for that. Makes using YouTube easier for people who turn off their comments to tell whether the video is good or not. This is the project:[https://www.returnyoutubedislike.com/](https://www.returnyoutubedislike.com/)

**Comment by ulyngs** [comment]
Good idea --- however, looking at the project it seems that it's not simple to add back the dislike button. It seems that the Return YouTube Dislike now just adds a dislike button, and then the dislikes shown are just from people who use the Return YouTube Dislike extension, because YouTube doesn't let you access the dislike information anymore.

However, if you like the Return YouTube Dislike extension, couldn't you simply use this on *in addition* to MindShield? Or do they interfere with each other somehow? :)
